### ISSUE TITLE
structures generating in the wrong biome on default super flat worlds

### ISSUE THREAD

**Issue by stophallucinating** [BarionLP/DungeonsEnhanced#11] opened 2022-03-13 02:41 UTC
Description: i have found a mushroom house and a miners house in the default plains super flat world even though i did not change anything in the biome option in the config for those two structures

Version:

Minecraft v1.16.5
Forge v36.2.30
Structure Gel API v1.7.8
Dungeons Enhanced v1.6

Screenshots:
![image](https://user-images.githubusercontent.com/41582097/158042495-548ceb2f-c251-4e50-829f-4ab100d3e852.png)
![image](https://user-images.githubusercontent.com/41582097/158042541-1fa9a18d-585a-4430-a21d-3b5bb2e6935b.png)

**Comment by BarionLP** [comment] 2022-03-13 05:56
this is a Vanilla bug, fixed in 1.18.2

**Comment by BarionLP** [comment] 2022-03-19 11:46
actually I can't reproduce it

**Comment by stophallucinating** [comment] 2022-03-19 14:02
yes
mod list: 
  AIReducer-1.16-0.1.0
  citadel-1.8.1-1.16.5
  dungeons_enhanced-1.16.5-1.6
  EntityCulling-1.16.5-2.1.6
  ferritecore-2.1.0-forge
  iceandfire-2.1.9-1.16.5
  jei-1.16.5-7.7.1.150
  lycanitesmobs-1.16.5-2.3.3.3
  Neat+1.7-27
  RoadRunner-mc1.16.5-1.4.0
  ScalingHealth-1.16.5-4.0.5+5
  silent-lib-1.16.3-4.9.6
  structure_gel-1.16.5-1.7.8
  Waystones_1.16.5-7.6.4
  XaerosWorldMap_1.20.3.1_Forge_1.16.5

and heres the config if you want
  https://drive.google.com/drive/folders/1K4bM_5XwCnwer1e1UzKpE2eN66SJ2gFH?usp=sharing

**Comment by BarionLP** [comment] 2022-03-29 08:00
I can't reproduce it, 
I might try it again in the future but I leave it for now as it doesn't seem to be game breaking

**Closed by BarionLP** 2022-03-29 08:00 UTC
Labels: bug
